#### Instruction (Read this)
- Use this template to develop your project. Do not change the steps. 
- For each step, you may add additional cells if needed.
- But remove <b>unnecessary</b> cells to ensure the notebook is readable.
- Marks will be <b>deducted</b> if the notebook is cluttered or difficult to follow due to excess or irrelevant content.
- <b>Briefly</b> describe the steps in the "Description:" field.
- <b>Do not</b> submit the dataset. 
- The submitted jupyter notebook will be executed using the uploaded dataset in eLearn.

#### Group Information

Group No: 

- Member 1:MUHAMMAD DANISH AIMAN BIN MUHAMMAD NAZIR
- Member 2:MUHAMMAD AMMAR BIN ADNAN
- Member 3:ARDY QAWI BIN HASHIM
- Member 4:MAHDIL ASHRONIE BIN MUHAMAD MURTADZA

#### Import libraries

In [1]:
%config Completer.use_jedi=False # comment if not needed
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
warnings.filterwarnings('ignore')

#### Load the dataset

In [2]:
df = pd.read_csv('risk_factors.csv', na_values='?')

In [3]:
print("Dataframe shape: ", df.shape)

Dataframe shape:  (858, 36)

In [4]:
print("Dataframe first 10 rows: ")
df.head(10)

Dataframe first 10 rows:

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,NaN,1.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.4,0.0,0.0,1.0,...,NaN,NaN,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.0,1.0,2.0,1.0,...,NaN,NaN,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,NaN,NaN,1,0,1,1,0,0,0,0
9,44,3.0,15.0,NaN,1.0,1.266973,2.8,0.0,0.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0

In [5]:
df.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
STDs: Time since first diagnosis      float64
STDs: Time since last diagnosis       float64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
dtype: object

In [6]:
df.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
count,858.000000,832.000000,851.000000,802.000000,845.000000,845.000000,845.000000,750.000000,750.000000,741.000000,...,71.000000,71.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,26.820513,2.527644,16.995300,2.275561,0.145562,1.219721,0.453144,0.641333,2.256419,0.112011,...,6.140845,5.816901,0.020979,0.010490,0.020979,0.027972,0.040793,0.086247,0.051282,0.064103
std,8.497948,1.667760,2.803355,1.447414,0.352876,4.089017,2.226610,0.479929,3.764254,0.315593,...,5.895024,5.755271,0.143398,0.101939,0.143398,0.164989,0.197925,0.280892,0.220701,0.245078
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,25.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,...,4.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,18.000000,3.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,...,8.000000,7.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,1.000000,37.000000,37.000000,1.000000,30.000000,1.000000,...,22.000000,22.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### Split the dataset
Split the dataset into training, validation and test sets.

In [7]:
target = df[['Hinselmann', 'Schiller', 'Citology', 'Biopsy']]
X = df.drop(['Hinselmann', 'Schiller', 'Citology', 'Biopsy'], axis=1)

In [8]:
# get number of row that has value of at least 1 among the 4 target
collective_target = (target.sum(axis=1) > 0).astype(int)

# Count the positive (1) and negative (0) values
positive_count = collective_target.sum()
negative_count = len(collective_target) - positive_count

# assign the newly formed binary target as y
df['target'] = collective_target
y = df[['target']]

print(f"{positive_count, negative_count}")

(102, 756)

Since we detected that the data set is hugely imbalanced in the positive and negative value. We decied to split the dataset using stratify method which will preserve the weight of positive and negative value within the test and train dataset.

In [9]:
seed_num = 42 # initialize seed number

# Create a stratify key which can be used to help split the data
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=seed_num) # random_state is set to a value for reproducible output.

# Create a second stratify key for futher spliting of the dataset
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=2/3, stratify=y_temp, random_state=seed_num)

print("Dataset Shape:")
print(f"Training: {X_train.shape}")
print(f"Validation: {X_val.shape}")
print(f"Test: {X_test.shape}")


train_count = (y_train.sum(axis=1) > 0).astype(int)
val_count = (y_val.sum(axis=1) > 0).astype(int)
test_count = (y_test.sum(axis=1) > 0).astype(int)
print("\nDataset Positive/Negative count:")
print(f"Training: {train_count.sum()}/{len(train_count) - train_count.sum()}")
print(f"Validation: {val_count.sum()}/{len(val_count) - val_count.sum()}")
print(f"Test: {test_count.sum()}/{len(test_count) - test_count.sum()}")

Dataset Shape:
Training: (600, 32)
Validation: (86, 32)
Test: (172, 32)

Dataset Positive/Negative count:
Training: 71/529
Validation: 10/76
Test: 21/151

#### Data preprocessing
Perform data preprocessing such as normalization, standardization, label encoding etc.
______________________________________________________________________________________
Description:

In [10]:
X_train.shape

(600, 32)

In [11]:
X_train.dtypes

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
STDs: Time since first diagnosis      float64
STDs: Time since last diagnosis       float64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
dtype: object

In [12]:
X_train.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HIV,STDs:Hepatitis B,STDs:HPV,STDs: Number of diagnosis,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx
464,16,1.0,14.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0.0,0.0,0,NaN,NaN,0,0,0,0
540,20,3.0,16.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0,NaN,NaN,0,0,0,0
383,19,2.0,15.0,3.0,0.0,0.0,0.0,1.0,0.58,0.0,...,0.0,0.0,0.0,0,NaN,NaN,0,0,0,0
369,18,1.0,18.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0,NaN,NaN,0,0,0,0
678,32,1.0,19.0,1.0,0.0,0.0,0.0,1.0,0.25,0.0,...,0.0,0.0,0.0,0,NaN,NaN,0,0,0,0

In [13]:
X_train.describe()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HIV,STDs:Hepatitis B,STDs:HPV,STDs: Number of diagnosis,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx
count,600.000000,583.000000,596.000000,560.000000,592.000000,592.000000,592.000000,523.000000,523.000000,516.000000,...,525.000000,525.000000,525.0,600.000000,48.000000,48.000000,600.000000,600.000000,600.000000,600.000000
mean,26.843333,2.560892,17.001678,2.278571,0.160473,1.393081,0.549388,0.659656,2.252303,0.108527,...,0.030476,0.001905,0.0,0.086667,5.583333,5.104167,0.018333,0.008333,0.020000,0.021667
std,8.315891,1.726879,2.798859,1.445827,0.367355,4.448927,2.465020,0.474279,3.743867,0.311347,...,0.172057,0.043644,0.0,0.309810,5.334885,5.041275,0.134266,0.090982,0.140117,0.145714
min,13.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,2.000000,15.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,2.000000,17.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,...,0.000000,0.000000,0.0,0.000000,4.000000,3.000000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,3.000000,18.000000,3.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,7.000000,7.000000,0.000000,0.000000,0.000000,0.000000
max,84.000000,28.000000,32.000000,11.000000,1.000000,37.000000,37.000000,1.000000,30.000000,1.000000,...,1.000000,1.000000,0.0,3.000000,21.000000,21.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
print(X_train.isnull().sum())

Age                                     0
Number of sexual partners              17
First sexual intercourse                4
Num of pregnancies                     40
Smokes                                  8
Smokes (years)                          8
Smokes (packs/year)                     8
Hormonal Contraceptives                77
Hormonal Contraceptives (years)        77
IUD                                    84
IUD (years)                            84
STDs                                   75
STDs (number)                          75
STDs:condylomatosis                    75
STDs:cervical condylomatosis           75
STDs:vaginal condylomatosis            75
STDs:vulvo-perineal condylomatosis     75
STDs:syphilis                          75
STDs:pelvic inflammatory disease       75
STDs:genital herpes                    75
STDs:molluscum contagiosum             75
STDs:AIDS                              75
STDs:HIV                               75
STDs:Hepatitis B                       75
STDs:HPV                               75
STDs: Number of diagnosis               0
STDs: Time since first diagnosis      552
STDs: Time since last diagnosis       552
Dx:Cancer                               0
Dx:CIN                                  0
Dx:HPV                                  0
Dx                                      0
dtype: int64

In [15]:
# Function to clean, drop column
def clean_dataset(df):
    # Convert boolean-like columns to proper boolean data types
    boolean_cols = [
        'Smokes', 'Smokes (years)', 'Smokes (packs/year)', 'Hormonal Contraceptives', 'IUD',
        'STDs', 'STDs:condylomatosis', 'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
        'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis', 'STDs:pelvic inflammatory disease',
        'STDs:genital herpes', 'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV', 'STDs:Hepatitis B',
        'STDs:HPV', 'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx'
    ]

    # Convert boolean-like columns to numeric
    df[boolean_cols] = df[boolean_cols].apply(pd.to_numeric, errors='coerce')

    # Replace values greater than 0 with 1, leave missing values untouched
    df[boolean_cols] = df[boolean_cols].applymap(lambda x: 1 if x > 0 else x)
    
    # Dropping the column that has too many missing value
    df = df.drop(['STDs: Time since first diagnosis', 'STDs: Time since last diagnosis'], axis=1)

    # Loop through columns and fill missing values with mode
    for column in df.columns:
        if df[column].isnull().any():  # Check if column has null values
            imputer = SimpleImputer(strategy='most_frequent')
            df[column] = imputer.fit_transform(df[[column]])
            
    return df

In [16]:
# Clean the dataset
X_train = clean_dataset(X_train)
# performing the same data preprocessing to the validation and test dataset
X_val = clean_dataset(X_val)
X_test = clean_dataset(X_test)

#### Feature Selection
Perform feature selection to select the relevant features.
______________________________________________________________________________________
Description:

In [17]:
from sklearn.ensemble import RandomForestClassifier

# Train the Random Forest model
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the random forest classifier
rf.fit(X_train, y_train)

# Get the feature importances
importances = rf.feature_importances_

# Create a list of tuples (feature, importance) and sort by importance in descending order
sorted_features = sorted(zip(X.columns, importances), key=lambda x: x[1], reverse=True)

# Print the sorted feature importances
for feature, importance in sorted_features:
    print(f"{feature}: {importance}")

Age: 0.22073681843335158
Hormonal Contraceptives (years): 0.17418163472597992
First sexual intercourse: 0.16281740081642276
Num of pregnancies: 0.11092744016073863
Number of sexual partners: 0.10442824063246
Hormonal Contraceptives: 0.029725290183546225
IUD (years): 0.024030019687575472
STDs: Time since first diagnosis: 0.023987603004321834
Dx:Cancer: 0.021095344132269198
STDs (number): 0.01885731033935962
STDs: Number of diagnosis: 0.013670337689947902
Smokes: 0.012804485925770952
Smokes (packs/year): 0.0107663846204771
Smokes (years): 0.010137264953515026
STDs:HIV: 0.0100622991435994
STDs:vulvo-perineal condylomatosis: 0.009586087965342308
IUD: 0.008817816476302046
STDs:condylomatosis: 0.007523784744225236
STDs:genital herpes: 0.006735789494407757
Dx:CIN: 0.006085749483377927
STDs: 0.0046510511375675865
STDs:syphilis: 0.004146250062740725
STDs:vaginal condylomatosis: 0.0019675597881901622
STDs: Time since last diagnosis: 0.0012849482494781833
STDs:Hepatitis B: 0.000931099281072285
STDs:pelvic inflammatory disease: 4.198886796022092e-05
STDs:cervical condylomatosis: 0.0
STDs:molluscum contagiosum: 0.0
STDs:AIDS: 0.0
STDs:HPV: 0.0

From the random forest feature selection, we will select the top 5 features with highest importance which are:

* Age: 0.20369740849872817
* Hormonal Contraceptives (years): 0.17443858513370752
* First sexual intercourse: 0.1671267048369037
* Num of pregnancies: 0.11944050831390075
* Number of sexual partners: 0.10967420508589303

In [18]:
# create a dataframe with the selected feature
X_train = X_train[['Age', 'Hormonal Contraceptives (years)', 'First sexual intercourse', 'Num of pregnancies', 'Number of sexual partners']]
X_val = X_val[['Age', 'Hormonal Contraceptives (years)', 'First sexual intercourse', 'Num of pregnancies', 'Number of sexual partners']]
X_test = X_test[['Age', 'Hormonal Contraceptives (years)', 'First sexual intercourse', 'Num of pregnancies', 'Number of sexual partners']]

# standardized the value to accomodate outlier
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.fit_transform(X_val)
X_test = scaler.fit_transform(X_test)

#### Data modeling
Build the machine learning models. You must build atleast two (2) predictive models. One of the predictive models must be either Decision Tree or Support Vector Machine.
______________________________________________________________________________________
Description:

#### Evaluate the models
Perform a comparison between the predictive models. <br>
Report the accuracy, recall, precision and F1-score measures as well as the confusion matrix if it is a classification problem. <br>
Report the R2 score, mean squared error and mean absolute error if it is a regression problem.
______________________________________________________________________________________
Description: